# load rules
include: "rules/common.smk"
include: "rules/fastp.smk"
include: "rules/getorganelle.smk"
include: "rules/assembled_sequence.smk"
include: "rules/seqkit.smk"

def get_assembled_samples(wildcards):
    ck_output = checkpoints.assembled_sequence.get(**wildcards).output[0]
    return expand(
        rules.seqkit.output,
        sample=glob_wildcards(os.path.join(ck_output, "{sample}.fasta")).sample,
    )

# one rule to rule them all :)
rule all:
    input:
        get_assembled_samples
