# load rules
include: "rules/common.smk"
include: "rules/fastp.smk"
include: "rules/getorganelle.smk"
include: "rules/assembled_sequence.smk"
include: "rules/seqkit.smk"
include: "rules/aggregate.smk"


# one rule to rule them all :)
rule all:
    input:
        "results/report.txt"
